#!/bin/bash

export LANG=C

TMPDIR=$(mktemp -d)
trap "rm -rf '${TMPDIR}'" EXIT

#KEYSERVER='hkp://pgp.ustc.edu.cn'
#KEYSERVER='hkp://pool.sks-keyservers.net'
#KEYSERVER='hkp://pgp.mit.edu'
KEYSERVER='hkp://keys.gnupg.net'
#KEYSERVER='hkp://pgp.nic.ad.jp'
#KEYSERVER='hkps://keys.mailvelope.com'
#KEYSERVER='hkp://hkps.pool.sks-keyservers.net'
#KEYSERVER='hkp://keyserver.ubuntu.com'
GPG="gpg --quiet --batch --no-tty --no-permission-warning --keyserver "${KEYSERVER}" --homedir ${TMPDIR}"

pushd "$(dirname "$0")" >/dev/null

$GPG --gen-key <<EOF
%echo Generating Arch Linux eyun Keyring keychain master key...
Key-Type: RSA
Key-Length: 1024
Key-Usage: sign
Name-Real: Arch Linux eyun Keyring Keychain Master Key
Name-Email: eyun-keyring@localhost
Expire-Date: 0
%no-protection
%no-ask-passphrase
%commit
%echo Done
EOF

rm -rf master{,-revoked} packager{,-revoked} eyun-{trusted,revoked}
mkdir master packager packager-revoked

# master-keyids
while read -ra data; do
	keyid="${data[0]}"
	username="${data[@]:1}"
	${GPG} --recv-keys ${keyid} &>/dev/null
	printf 'minimize\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	${GPG} --yes --lsign-key ${keyid} &>/dev/null
	${GPG} --armor --no-emit-version --export ${keyid} >> master/${username}.asc
	echo "${keyid}:4:" >> eyun-trusted
done < master-keyids
${GPG} --import-ownertrust < eyun-trusted 2>/dev/null

# master-revoked-keyids
while read -ra data; do
	keyid="${data[0]}"
	username="${data[1]}"
	"${GPG[@]}" --comment "revoked master-key: ${username} (${keyid})" --export ${keyid} >> master-revoked/${username}.asc
	echo "${keyid}" >> eyun-revoked
done < master-revoked-keyids

# packager-keyids
while read -ra data; do
	keyid="${data[0]}"
	${GPG} --recv-keys ${keyid} &>/dev/null
done < packager-keyids
while read -ra data; do
	keyid="${data[0]}"
	username="${data[@]:1}"
	printf 'clean\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	if ! ${GPG} --list-keys --with-colons ${keyid} 2>/dev/null | grep -Pq '^pub:(f|-):'; then
		echo "key is not fully trusted: ${keyid} ${username}"
	else
		${GPG} --armor --no-emit-version --export ${keyid} >> packager/${username}.asc
	fi
done < packager-keyids

# packager-revoked-keyids
while read -ra data; do
	keyid="${data[0]}"
	username="${data[2]}"
	${GPG} --recv-keys ${keyid} &>/dev/null
	printf 'clean\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	if ! ${GPG} --list-keys --with-colons ${keyid} 2>/dev/null | grep -Pq '^pub:(f|-):'; then
		${GPG} --armor --no-emit-version --export ${keyid} >> packager-revoked/${username}.asc
		echo "${keyid}" >> eyun-revoked
	else
		echo "key is still fully trusted: ${keyid} ${username}"
	fi
done < packager-revoked-keyids

cat master/*.asc master-revoked/*.asc packager/*.asc packager-revoked/*.asc > eyun.gpg

popd >/dev/null
